WIP: PR for Storage Credentials & External Storage Location
databrickslabs/terraform-provider-databricks pull request #1008
Opened 2021-12-29 13:52 UTC by stikkireddy

2021-12-29 14:06 UTC, nfx requested changes

2021-12-29 14:06 UTC, nfx commented on catalog/resource_storage_credentials.go
> +func (a StorageCredentialsAPI) create(cm StorageCredentialConfig) (mi StorageCredentialConfig, err error) {
`cm` -> `scc`. but why do we need to return it?...

simply make `scc *StorageCredentialConfig` as the argument and return error from post straight away

2021-12-29 14:06 UTC, nfx commented on catalog/resource_storage_credentials.go
> +func (a StorageCredentialsAPI) get(id string) (sci StorageCredentialConfig, err error) {
`sci` -> `scc`

2021-12-29 14:06 UTC, nfx commented on catalog/resource_storage_credentials.go
> +func (a StorageCredentialsAPI) update(storageCredentialsName string, info StorageCredentialConfig) error {
`info` -> `scc`

2021-12-29 14:06 UTC, nfx commented on catalog/resource_storage_credentials.go
> +		Update: func(ctx context.Context, d *schema.ResourceData, c *common.DatabricksClient) error {
missing test for update happy flow (name + aws role) and force new flow - changing one of the things that could be changeable, but force new.

2021-12-29 14:14 UTC, stikkireddy commented on catalog/resource_storage_credentials.go
> +	Owner       string                 `json:"owner,omitempty" tf:"computed"`
cannot create storage credentials: CreateStorageCredential credential_info.owner can not be provided. is the error we get when set it during the create request

2021-12-30 14:20 UTC, nfx approved these changes
changes applied

2021-12-30 14:33 UTC, merged