Add data source for service principals
databrickslabs/terraform-provider-databricks pull request #1207
Opened 2022-03-21 14:48 UTC by rondefreitas

- return `application_id` from `databricks_current_user` if that user is a Service Principal
- add `databricks_service_principal` data source (maybe could enhance later with a display name lookup, but for now, you need the application id)
- add tests for data source
- update documentation

Hopefully this isn't too shabby... first time writing anything in Go.

2022-03-21 19:59 UTC, nfx requested changes

2022-03-21 19:59 UTC, nfx commented on docs/data-sources/current_user.md
> +* `application_id` - Application ID of the [service principal](../resources/service_principal.md) if the currently logged-in user is a service principal, e.g. `813073e7-3b08-4c0d-8619-39bcfa4ac632`
can you anonymise `813073e7-3b08-4c0d-8619-39bcfa4ac632`?

2022-03-21 19:59 UTC, nfx commented on docs/data-sources/service_principal.md
> +Retrieves information about [databricks_service_principal](../resources/user.md).
`user.md` -> `service_principal.md`

2022-03-21 19:59 UTC, nfx commented on scim/data_service_principal.go
> +	return &schema.Resource{
please rewrite with the new data resource framework: https://github.com/databrickslabs/terraform-provider-databricks/blob/master/jobs/data_jobs.go

2022-03-21 20:58 UTC, rondefreitas commented on docs/data-sources/service_principal.md
> +Adding service principal "813073e7-3b08-4c0d-8619-39bcfa4ac632" to administrative group
will do @nfx . That was actually randomly generated for the docs, but I'll update accordingly.

2022-03-29 10:08 UTC, nfx commented
@rondefreitas any update on review comments?

2022-04-21 09:29 UTC, nfx commented
@rondefreitas are you still interested in finishing this pull request?

2022-05-30 10:25 UTC, nfx commented
@rondefreitas are you still interested in finishing this pull request?

2022-06-10 10:24 UTC, closed without merging