add GCS to cluster init script storage
databrickslabs/terraform-provider-databricks pull request #1308
Opened 2022-05-11 21:26 UTC by neilbest-db

Intended to fix #1203.

Found no appropriate tests to mimic.

2022-05-12 06:29 UTC, alexott commented
Please add documentation

2022-05-14 22:16 UTC, nfx requested changes
Small change required

2022-05-14 22:16 UTC, nfx commented on go.mod
> +	github.com/katbyte/terrafmt v0.4.0 // indirect
Remove this. It doesn't belong to binary

2022-05-15 20:22 UTC, nfx commented on go.mod
> +	github.com/katbyte/terrafmt v0.4.0 // indirect
```suggestion
```

2022-05-17 22:57 UTC, nfx approved these changes

2022-05-17 22:59 UTC, merged