Clarify optionality of `databricks_mws_workspaces`.`deployment_name` in docs and examples
databrickslabs/terraform-provider-databricks pull request #1315
Opened 2022-05-17 18:49 UTC by easel

Fixes #1314

2022-05-17 19:06 UTC, nfx requested changes

2022-05-17 19:06 UTC, nfx commented on docs/guides/aws-private-link-workspace.md
> +  # only set this if you have worked with databricks to set a deployment name
probably rename this field from HCL example and add this sentence in the attribute reference in docs/resources/mws_workspaces.md.

2022-05-17 19:06 UTC, nfx commented on docs/resources/mws_workspaces.md
> +* `deployment_name` - (Optional) part of URL: `https://<deployment-name>.cloud.databricks.com`. Must be configured out of band by your databricks rep.
```suggestion
* `deployment_name` - (Optional) part of URL as in `https://<prefix>-<deployment-name>.cloud.databricks.com`. Deployment name cannot be used until a deployment name prefix is defined. Please contact your Databricks representative. Once a new deployment prefix is added/updated, it only will affect the new workspaces created.
```

2022-05-18 18:21 UTC, nfx commented on docs/guides/aws-private-link-workspace.md
> +  # only set this if you have worked with databricks to set a deployment name
```suggestion
```

2022-05-18 18:21 UTC, nfx commented on docs/guides/aws-private-link-workspace.md
> +  # deployment_name            = local.prefix
```suggestion
```

2022-05-18 18:21 UTC, nfx commented on docs/resources/mws_private_access_settings.md
> +  # only set this if you have worked with databricks to set a deployment name
```suggestion
```

2022-05-18 18:21 UTC, nfx commented on docs/resources/mws_private_access_settings.md
> +  # deployment_name            = local.prefix
```suggestion
```

2022-05-18 18:21 UTC, nfx commented on docs/resources/mws_workspaces.md
> +  # deployment_name = var.prefix
```suggestion
```

2022-05-18 18:23 UTC, nfx approved these changes

2022-05-18 18:36 UTC, merged

2022-05-18 19:20 UTC, easel commented
Thanks for the merge!