Pr/256
databrickslabs/terraform-provider-databricks pull request #260
Opened 2020-08-19 13:23 UTC by nfx

2020-08-19 13:24 UTC, nfx reviewed
LGTM

2020-08-19 13:25 UTC, nfx commented
fixes conflicts in #256

2020-08-19 13:27 UTC, TravisBuddy commented
Hey @nfx,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;719275062">View build log</a>

###### TravisBuddy Request Identifier: aaaed6f0-e21f-11ea-9f3b-59dd2f7037a2

2020-08-19 13:30 UTC, TravisBuddy commented
Hey @nfx,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;719275454">View build log</a>

###### TravisBuddy Request Identifier: 1e3608f0-e220-11ea-9f3b-59dd2f7037a2

2020-08-19 14:13 UTC, sdebruyn requested changes

2020-08-19 14:13 UTC, sdebruyn commented on compute/resource_instance_pool.go
> +				Optional: true,
It should say Optional in the docs as well (that was the merge conflict), it's saying Required now

2020-08-19 18:11 UTC, TravisBuddy commented
Hey @nfx,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;719365162">View build log</a>

###### TravisBuddy Request Identifier: 741ec370-e247-11ea-9f3b-59dd2f7037a2

2020-08-20 08:44 UTC, TravisBuddy commented
Hey @nfx,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;719522938">View build log</a>

###### TravisBuddy Request Identifier: 4aa00cf0-e2c1-11ea-9f3b-59dd2f7037a2

2020-08-20 11:55 UTC, merged