Improve library await
databrickslabs/terraform-provider-databricks pull request #335
Opened 2020-09-22 19:12 UTC by nfx

Fix #315

2020-09-22 19:16 UTC, TravisBuddy commented
## Travis tests have failed

Hey @nfx,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 2nd Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;jobs&#x2F;729409186">View build log</a>


<details>
  <summary>
    <strong>
     curl -sSL &quot;https:&#x2F;&#x2F;github.com&#x2F;gotestyourself&#x2F;gotestsum&#x2F;releases&#x2F;download&#x2F;v0.4.2&#x2F;gotestsum_0.4.2_linux_amd64.tar.gz&quot; | sudo tar -xz -C &#x2F;usr&#x2F;local&#x2F;bin gotestsum
    </strong>
  </summary>

```
The command "curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v0.4.2/gotestsum_0.4.2_linux_amd64.tar.gz" | sudo tar -xz -C /usr/local/bin gotestsum" exited with 0.
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
golangci/golangci-lint info checking GitHub for tag 'v1.25.0'
golangci/golangci-lint info found version: 1.25.0 for v1.25.0/linux/amd64
golangci/golangci-lint info installed /home/travis/gopath/bin/golangci-lint
The command "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0" exited with 0.
$ time make lint
✓ Linting source code with golangci-lint make sure you run make fmt ...
internal/qa/testing.go:141: File is not `gofmt`-ed with `-s` (gofmt)
		if diags.HasError()  {
compute/libraries_test.go:18: File is not `gofmt`-ed with `-s` (gofmt)
			LibraryStatus{
compute/resource_cluster_test.go:102: File is not `gofmt`-ed with `-s` (gofmt)
				ExpectedRequest: ClusterLibraryList {
compute/resource_cluster.go:214:2: naked return in func `waitForLibrariesInstalled` with 32 lines of code (nakedret)
	return
	^
Makefile:10: recipe for target 'lint' failed
make: *** [lint] Error 1

real	0m30.733s
user	0m53.490s
sys	0m1.843s
The command "time make lint" exited with 2.
$ time make test
✓ Running tests...
∅  .
✓  access (129ms) (coverage: 83.5% of statements)
✓  access/acceptance (49ms)
✓  common (274ms) (coverage: 68.2% of statements)
✓  compute/acceptance (23ms)
✓  identity (96ms) (coverage: 42.4% of statements)
✓  compute (1.819s) (coverage: 76.4% of statements)
✓  internal (10ms) (coverage: 67.5% of statements)
✓  internal/qa (14ms) (coverage: 54.0% of statements)
✓  identity/acceptance (22ms)
∅  internal/acceptance
✓  internal/sanity (40ms) (coverage: 100.0% of statements)
✓  mws (1.102s) (coverage: 70.5% of statements)
✓  mws/acceptance (22ms)
✓  provider (286ms) (coverage: 70.7% of statements)
✓  storage (131ms) (coverage: 73.5% of statements)
✓  storage/acceptance (23ms)
✓  workspace/acceptance (21ms)
✓  workspace (10.058s) (coverage: 62.9% of statements)

DONE 572 tests, 65 skipped in 37.058s

real	0m37.066s
user	0m45.346s
sys	0m5.812s
The command "time make test" exited with 0.
$ time make build
✓ Building source code with go build...

real	0m2.955s
user	0m3.627s
sys	0m0.431s
The command "time make build" exited with 0.
store build cache
changes detected (content changed, file is created, or file is deleted):\n/home/travis/.cache/go-build/01/0179e2f9f536df38866d725ee7607ba4e17fab58b35b115b8e3e3b39df8ae1d7-a
/home/travis/.cache/go-build/01/01edcde411789ca3ef815f5e513b35ea992afc91f13c4daf5c8d20b90d407680-a
/home/travis/.cache/go-build/01/01efa3ed220fac1988c0defea7ff4eaf1841521e410f79a00fcdab6cea4fbef4-a
/home/travis/.cache/go-build/01/01f49f9c5d615587125ec9ba9e1df2070cd093b585d1a80455bc701cb47a3f5e-d
/home/travis/.cache/go-build/02/0235ebe42646c5b7daff924db1caef68b438e61d3480f487afb9936438dcd880-d
/home/travis/.cache/go-build/02/0260fa3e22d32de9301fc41974cb4254859bb9466dbb52dc6bb7bc8b18ac0b2f-a
/home/travis/.cache/go-build/03/03e8118e220def892a457ca8bfd0e30987e9aeac22f15e7d940825cdf4474479-a
/home/travis/.cache/go-build/04/049877d8bb7c7e94919406821a7784bdc8040a185de65bae7a5d786acab9ba61-a
/home/travis/.cache/go-build/05/0559c9210ce0b9764c16bd194aeebd58bbcb71048a44064f44801d84baa2f8e9-a
/home/travis/.cache/go-build/05/05ca1893ac6928433506d1397c7236acbda78d1052b6b8235c73f3de7c18d76f-a
/home/trav\n...
changes detected, packing new archive
uploading PR.335/cache--linux-xenial-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--go-1.14.x.tgz
cache uploaded


Done. Your build exited with 1.
```

</details>


<details>
  <summary>
    <strong>
     curl -sSfL https:&#x2F;&#x2F;raw.githubusercontent.com&#x2F;golangci&#x2F;golangci-lint&#x2F;master&#x2F;install.sh | sh -s -- -b $(go env GOPATH)&#x2F;bin v1.25.0
    </strong>
  </summary>

```
golangci/golangci-lint info checking GitHub for tag 'v1.25.0'
golangci/golangci-lint info found version: 1.25.0 for v1.25.0/linux/amd64
golangci/golangci-lint info installed /home/travis/gopath/bin/golangci-lint
```

</details>


<details>
  <summary>
    <strong>
     time make lint
    </strong>
  </summary>

```
✓ Linting source code with golangci-lint make sure you run make fmt ...
internal/qa/testing.go:141: File is not `gofmt`-ed with `-s` (gofmt)
		if diags.HasError()  {
compute/libraries_test.go:18: File is not `gofmt`-ed with `-s` (gofmt)
			LibraryStatus{
compute/resource_cluster_test.go:102: File is not `gofmt`-ed with `-s` (gofmt)
				ExpectedRequest: ClusterLibraryList {
compute/resource_cluster.go:214:2: naked return in func `waitForLibrariesInstalled` with 32 lines of code (nakedret)
	return
	^
Makefile:10: recipe for target 'lint' failed
make: *** [lint] Error 1

real	0m30.733s
user	0m53.490s
sys	0m1.843s
```

</details>


###### TravisBuddy Request Identifier: 10ba6c40-fd08-11ea-a56a-67316b5b87cd

2020-09-22 19:19 UTC, TravisBuddy commented
Hey @nfx,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;729409593">View build log</a>

###### TravisBuddy Request Identifier: 8b6c07a0-fd08-11ea-a56a-67316b5b87cd

2020-09-23 09:59 UTC, TravisBuddy commented
Hey @nfx,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;729570919">View build log</a>

###### TravisBuddy Request Identifier: 77bd4fe0-fd83-11ea-a706-8f9ec0eccd66

2020-09-23 11:33 UTC, alexott requested changes
there will be conflict in the CronSchedule struct - this change is not required for this PR

2020-09-23 11:33 UTC, alexott commented on compute/model.go
> +	PauseStatus          string `json:"pause_status,omitempty" tf:"computed"`
This will conflict with #334

2020-09-23 11:33 UTC, alexott commented on compute/resource_cluster.go
> +	err = resource.Retry(30*time.Minute, func() *resource.RetryError {
Will it make sense to move this to constant, defined at the beginning?

2020-09-23 16:07 UTC, nfx commented on compute/model.go
> +	PauseStatus          string `json:"pause_status,omitempty" tf:"computed"`
why? it's the same change

2020-09-23 16:07 UTC, merged