Don't restart cluster on changes that doesn't affect it (issue #379)
databrickslabs/terraform-provider-databricks pull request #385
Opened 2020-10-23 14:56 UTC by alexott

This PR adds detection of what cluster parameters were changed, and call `/clusters/edit`
only we changed parameters that are related to cluster directly, not things like
`is_pinned` or `library`...

This fixes #379

2020-10-23 15:38 UTC, TravisBuddy commented
Hey @alexott,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;738331264">View build log</a>

###### TravisBuddy Request Identifier: c110c300-1545-11eb-aff7-dd8cbeb067cc

2020-10-23 15:47 UTC, nfx commented on compute/resource_cluster.go
> +		if d.HasChange(k) {
can you add a unit test to it? :)

2020-10-23 15:48 UTC, nfx requested changes
can you add a unit-test?

2020-10-23 17:46 UTC, nfx commented on compute/resource_cluster.go
> +		if strings.HasPrefix(k, "library") || k == "is_pinned" {
+ `libraries` key itself.

2020-10-23 17:47 UTC, nfx commented on compute/resource_cluster.go
> +		if strings.HasPrefix(k, "library") || k == "is_pinned" {
because `library_` is deprecated and would be removed in few weeks

2020-10-26 08:27 UTC, alexott commented
it's interesting question - about unit testing of "incremental" change.  I've looked through existing testing infrastructure, and couldn't figure out how to do a "single" change to the existing state - right now you need to provide complete state (with Spark version, etc.), but it will trigger the `/clusters/edit` as before...

2020-11-05 08:05 UTC, TravisBuddy commented
Hey @alexott,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;databrickslabs&#x2F;terraform-provider-databricks&#x2F;builds&#x2F;741573801">View build log</a>

###### TravisBuddy Request Identifier: bb5c8140-1f3d-11eb-bd2e-17a8c440c3de

2020-11-06 09:22 UTC, nfx approved these changes
I'll change it to 0.2.8 :)

2020-11-06 09:23 UTC, merged