Mark resources as new when doing import
databrickslabs/terraform-provider-databricks pull request #472
Opened 2021-01-27 20:18 UTC by alexott

This fixes #471

2021-01-27 20:30 UTC, stikkireddy commented
can we add the acceptance test for imports?

2021-01-27 20:42 UTC, nfx requested changes
Looks great! Small generic changes like this pay off humongous refactoring done before :) 

could you please test it with few random other resources than user and add as comment? This change affects literally all resources. I wonder if you could add an acceptance test for few random resources - user, group, secret. 

Please remove sdk v1 module from go.sum - probably got there by mistake. Also avoid getting it in, as we may get very weird classpath issues.

I’ll make sure to test that tomorrow.

2021-01-27 20:42 UTC, nfx commented on go.sum
> +github.com/hashicorp/terraform-plugin-sdk v1.16.0 h1:NrkXMRjHErUPPTHQkZ6JIn6bByiJzGnlJzH1rVdNEuE=
We shouldn’t add sdk v1 back. Can you make sure only v2 sdk is used?

2021-01-29 01:05 UTC, nfx approved these changes

2021-01-29 01:05 UTC, merged