Add resource for global init scripts
databrickslabs/terraform-provider-databricks pull request #488
Opened 2021-02-09 15:09 UTC by alexott

This fixes #295

2021-02-09 19:07 UTC, nfx requested changes
great work! comments:

1. i think it's more of `workspace` type of resource, not a compute.
2. Unit tests should be on resource CRUD, rather on API wrapper
3. `position` probably should be ignored and just returned as `computed`. e.g. not allowing to specify it.

2021-02-09 19:07 UTC, nfx commented on compute/resource_global_init_script.go
> +			scriptStatus, err := globalInitScriptsAPI.Get(scriptID)
`.Get` is already called by `Read` method (handled in `CommonResource`). so lines 72-76 are not needed

2021-02-09 19:07 UTC, nfx commented on compute/resource_global_init_script.go
> +			scriptStatus, err := globalInitScriptsAPI.Get(scriptID)
107-111 - also handled in common resource calling get

2021-02-09 19:07 UTC, nfx commented on docs/resources/global_init_script.md
> +    echo "hellp world"
![image](https://user-images.githubusercontent.com/259697/107414182-f2f9b800-6b11-11eb-89b9-d4add8612b48.png)

2021-02-09 19:07 UTC, nfx commented on docs/resources/global_init_script.md
> +* `position` (int, optional, default: 10000) the position of the script in the list of scripts.  With default value it's added at the end of the list.  The behavior of the REST API may lead to a situ
didn't finish sentence :) see my previous comments on this attribute

2021-02-09 19:11 UTC, alexott commented on compute/global_init_scripts.go
> +	err := a.client.Delete(a.context, "/global-init-scripts/"+scriptID, request)
that's a good question - per documentation we need path param only, but it doesn't work - raised the issue with docs team, but this requires investigation

2021-02-10 08:48 UTC, alexott commented
@nfx comments are addressed

2021-02-10 12:57 UTC, nfx approved these changes

2021-02-10 13:01 UTC, merged