Fix the lowercase of compute resources
databrickslabs/terraform-provider-databricks pull request #794
Opened 2021-08-22 14:51 UTC by KoenR3

Camelcase the category of a resource as this is what the platform expects.

This fixeds  #792

2021-08-22 14:58 UTC, nfx commented
@KoenR3 did you test it on all of AWS, Azure, and GCP workspaces?..

@alexott , could you review this, as you made the most recent changes there

2021-08-22 15:24 UTC, alexott commented
Current list on Azure is:

```
>curl -s -n -X GET "$DATABRICKS_HOST/api/2.0/clusters/list-node-types" -H "Authorization: Bearer $DATABRICKS_TOKEN"|jq '.node_types[]|.category'|sort |uniq -c
  14 "Compute Optimized"
   9 "GPU Accelerated"
   7 "General Purpose (HDD)"
  33 "General Purpose"
   4 "Memory Optimized (Remote HDD)"
  51 "Memory Optimized"
   9 "Storage Optimized"
```

I think that it makes sense  to use case-insensitive comparison in the code. I'll fix that

2021-08-23 06:49 UTC, alexott requested changes
see comment on GPU

It would be also useful to incorporate differences between clouds & show the command that could be used to extract the list of possible values, as this list changes from time to time (like, if we start support GPUs on GCP, etc.)

2021-08-23 06:49 UTC, alexott commented on docs/data-sources/node_type.md
>    * `GPU`
it should be `GPU Accelerated`.

2021-08-23 15:50 UTC, nfx commented on docs/data-sources/node_type.md
>    * `GPU`
@KoenR3 ^^

2021-08-25 08:34 UTC, alexott commented
@nfx can you merge this PR, I'll add clarifications on top of it.

2021-08-25 09:16 UTC, merged

2021-08-25 12:54 UTC, KoenR3 commented
Sorry about the late reply, swamped with work...

2021-08-25 12:55 UTC, alexott commented
no problem, understood...