Update secret scope validation to include `/` characters
databrickslabs/terraform-provider-databricks pull request #892
Opened 2021-11-02 22:03 UTC by tylangesmith

This PR fixes issue #888

2021-11-02 22:15 UTC, nfx requested changes
Please remove redundant unit tests and keep only one for creating. Url encoding and validation is the test focus, not already tested functionality.

2021-11-02 22:15 UTC, nfx commented on access/resource_secret_acl_test.go
> +func TestSecretsScopesAclsIntegration_ScopeWithSlash(t *testing.T) {
Test prefix must be "TestAcc"

2021-11-02 22:15 UTC, nfx commented on access/resource_secret_acl_test.go
> +func TestSecretsScopesAclsIntegration_ScopeWithSlash(t *testing.T) {
This test doesn't add value to provider - SDK layer doesn't perform validation, Terraform resource does.

Create a test in acceptance package instead and add a scope with a slash in name.

2021-11-02 22:15 UTC, nfx commented on access/resource_secret_acl_test.go
> +func TestResourceSecretACLRead_ScopeWithSlash_NotFound(t *testing.T) {
This test is not necessary

2021-11-02 22:15 UTC, nfx commented on access/resource_secret_acl_test.go
> +func TestResourceSecretACLRead_ScopeWithSlash_Error(t *testing.T) {
This test is not necessary as well - url encoding of a slash was tested by the first test added

2021-11-02 22:15 UTC, nfx commented on access/resource_secret_acl_test.go
> +func TestResourceSecretACLCreate_ScopeWithSlash(t *testing.T) {
Probably just keep this test, as it covers both read and create

2021-11-03 00:00 UTC, nfx approved these changes
Lgtm

2021-11-03 12:12 UTC, nfx commented
@tylangesmith please rebase onto latest master

2021-11-04 04:46 UTC, tylangesmith commented
Forgot to tag you this morning @nfx but I believe that should be rebased now

2021-11-04 08:35 UTC, nfx approved these changes

2021-11-04 09:45 UTC, merged