Update examples for Azure configuration
databrickslabs/terraform-provider-databricks pull request #987
Opened 2021-12-16 20:26 UTC by a2m1

I've faced with an issue that azurerm provider was passing an empty value to databricks provider. I was able to fix it only by using datasources. Noticed that similar information is provided in the guide after searching the source code [azure-workspace.md](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/guides/azure-workspace.md#data-resources-and-authentication-is-not-configured-errors) but it's not available while browsing the registry.

Related issue: https://github.com/hashicorp/terraform/issues/2430

2021-12-17 15:23 UTC, nfx requested changes

2021-12-17 15:23 UTC, nfx commented on docs/index.md
> +data "azurerm_databricks_workspace" "this" {
the examples do work most of the times like they were before. This PR seems to suggest a workaround with data resource, but does not explain why.

Please do not modify these examples and instead add a new paragraph with detailed explanation, issue reference (https://github.com/hashicorp/terraform/issues/2430), and code example. Make sure to modify azure workspace guide as well.

2021-12-21 08:12 UTC, nfx commented
hi @a2m1 , any update on review comments?

2021-12-22 01:26 UTC, a2m1 commented
Hey @nfx,
I will update it as a separate paragraph. The current example worked for me as well until one day when I didn't change any configuration and it just stopped working. To be honest I didn't find the root cause of my issue. But the issue was that `azurerm` wasn't providing information to the `databricks` provider and I was able to fix it by hardcoding static values (as workspace was already deployed) and later via the data source.

2021-12-22 07:07 UTC, alexott commented
@a2m1 you just need to put `depends_on = [azurerm_databricks_workspace.this]` into databricks resources - this will force them wait until workspace is created

2021-12-22 21:39 UTC, a2m1 commented
@alexott I wish it was that simple. Unfortunately, it didn't help

2021-12-22 22:18 UTC, closed without merging