databricks_dbfs_file data source minor fix and improvement
databrickslabs/terraform-provider-databricks pull request #993
Opened 2021-12-21 15:28 UTC by dugernierg

Current behavior of `limit_file_size` doesn't correspond to [the doc's argument description](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/data-sources/dbfs_file). Implemented expected behavior.

On v0.3.3, databricks_dbfs_file resource got a new `dbfs_path` attribute the data source never got. `dbfs_path` is useful to keep other resources declaration clean, such as when referencing a custom jar as a cluster library. databricks_dbfs_file data source should now mirror its resource counterpart and provide the same attributes.

2021-12-21 15:37 UTC, dugernierg commented
First attempt at contributing to this project. 

Changes haven't been tested locally yet. I admit I never used a provider that hasn't been released yet, so I'm unsure how to proceed. I'll figure this out in due time whenever I can spare an hour or two, but someone more experienced would certainly do it faster.

2021-12-22 14:54 UTC, nfx requested changes

2021-12-22 16:42 UTC, nfx commented
@dugernierg please see https://github.com/databrickslabs/terraform-provider-databricks/blob/master/CONTRIBUTING.md to get you started with testing procedures

2021-12-29 11:02 UTC, nfx commented
@dugernierg any update on this PR?

2021-12-29 20:50 UTC, dugernierg commented
On holidays, I will try to check the doc you gave me in the middle of next
week.

On Wed, 29 Dec 2021 at 12:02, Serge Smertin ***@***.***>
wrote:

> @dugernierg <https://github.com/dugernierg> any update on this PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/databrickslabs/terraform-provider-databricks/pull/993#issuecomment-1002538387>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQ5NRCX6PGKO3TDDIZAFJLUTLTGHANCNFSM5KQOEQIQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-01-04 11:23 UTC, nfx commented
@dugernierg any update on this PR?

2022-01-06 09:36 UTC, dugernierg commented
@nfx Sorry for the delayed response, I hadn't access to a development device until today. I'm checking the doc you provided me and will run the `make test` command asap.

2022-01-06 13:11 UTC, nfx commented
@dugernierg perfect! thank you for the update.

2022-01-17 11:24 UTC, nfx commented
@dugernierg any update on this PR?

2022-01-28 15:42 UTC, nfx commented
@dugernierg I'll close this PR due to inactivity. please open a new one with passing tests build.

2022-01-28 15:42 UTC, closed without merging